const menubtn = document.querySelector('#menu-btn')
menubtn.addEventListener('click',function(){document.body.classList.toggle('mobile_menu_active')
})
const modooscuro = document.querySelector('#modo-oscuro-btn')
modooscuro.addEventListener('click',function(){document.body.classList.toggle('modo-oscuro')
})
const logooscuro = document.querySelector('#logo-oscuro')
logooscuro.addEventListener(function(){document.body.classList.toggle('modo-oscuro')
})
